name       : libchardet
version    : 1.0.4
release    : 3
source     :
    - https://github.com/Joungkyun/libchardet/archive/1.0.4.tar.gz : dcd388b2b885c338ddf0c83afa8b99cc9d9e55b1106cd0be03eb9d327fb73374
license    : MPL-1.1
component  : programming.library
summary    : Mozilla's Universal Charset Detector C/C++ API
description: |
    Mozilla's Universal Charset Detector C/C++ AP
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
