name       : libchardet
version    : 1.0.4
release    : 2
source     :
    - http://ftp.oops.org/pub/oops/libchardet/libchardet-1.0.4.tar.bz2 : f43f5a63901f19780b5cd61ad130d432a9414e2e4da2abc0e1b80845895a7c33
license    : MPL-1.1
summary    : Mozilla's Universal Charset Detector C/C++ API
description: |
    Mozilla's Universal Charset Detector C/C++ AP
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
